### ISSUE TITLE
`/_debug/**`ページを追加して、アプリに関するデバッグを行いたい

### ISSUE THREAD

**Issue by imeankenshin** [KDG-Develop-Hub/social-web#35]
## 概要
開発サーバーのみにアクセスできるルート、`/_debug/**`を追加する。
同時に、任意で500エラーを起こして、エラー画面を表示させるテストページを実装する。

**Comment by imeankenshin** [comment]
@minoru-kinugasa-105 なんやかんやデバッグ用のためにこれ作ったけど、今回やりたいことって結局は500の表示がどうなりたいかってことだよね?
だったら、前にもう一つ提案した、その表示をコンポーネント化して、`/500`で確認できる、っていうのはどうかな?
これ実装してて思って、今後このデバッグ機能使うのもごくわずかなしてきて、たいして需要ない気がしてきた...

**Comment by minoru-kinugasa-105** [comment]
500ページをただ表示するっていうより、予期しないエラーが発生したときちゃんとcatchして表示できるかを確認したい、って感じです！
/_debug/ディレクトリにページを作る

**Comment by minoru-kinugasa-105** [comment]
500ページをただ表示するっていうより、予期しないエラーが発生したときちゃんとcatchして表示できるかを確認したい、って感じです！

あと、僕的には
❌ /_debug/ディレクトリにページを作る
⭕️  debug.vue などでデバッグ要項を1つのページにまとめる
を想像してました！
これなら、そこまで使うことがなくても置いておける感じするかなーと思いまして
