### ISSUE TITLE
綴るためのダイアログの実装

### ISSUE THREAD

**Issue by imeankenshin** [KDG-Develop-Hub/social-web#7]
## 概要
投稿を記述するためのダイアログを実装する。
ナビゲーションレールのFABを押すことで表示ができる。
## リンク
デザインの参照：https://www.figma.com/design/feJkoD1AFJ6NXsBEQ5xqF9/app?node-id=1559-1211&t=hmmx6LTOKxZVZTyC-11

**Comment by imeankenshin** [comment]
@okamuratakeru 
とりあえず大まかなUIは以上のPRで実装はできた、ありがとう！！👍
足りていない機能(画像アップロードや投票追加)は、ぞれぞれ別のPRで実装する方針でいるけど、それで良さそうですかね？🤔

**Comment by imeankenshin** [comment]
これで良さそうと判断したっ

**Comment by okamuratakeru** [comment]
@imeankenshin 
ごめん普通に気づかんかった。
ダイアログ画面の画像追加は、また違うイシュー立てるかんじ？
あとけんしんデザイン凝るから大まかに作ってくねー

**Comment by imeankenshin** [comment]
UI実装完了したし、めっちゃ遅れたけどクローズするね
